### ISSUE TITLE
Добавить try and catch (см. другой issue с подробностями)

### ISSUE THREAD

**Issue by IlyaPotseluev** [ESCA7A/XROM-1-ST-WEEK#7]
https://github.com/ESCA7A/XROM-1-ST-WEEK/blob/d7c8f83aec3732dfb0edc5f9530bd9ad0095caba/scripts/connect.php#L17

См. https://github.com/ESCA7A/XROM-1-ST-WEEK/issues/5

**Comment by ESCA7A** [comment]
@IlyaPotseluev спасибо большое за помощь, Илья!
